ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        host: 0.0.0.0
        port: 5000
    storage:
        driverClassName: "org.postgresql.Driver"
        jdbcURL: "jdbc:postgresql://amvera-klodmit-cnpg-languagebase-rw/languageapp"
        user: "klodmit"
        password: "228972"